//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSM_PaymentTerm
    {
        public int PaymentTermId { get; set; }
        public string PaymentTermName { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsDefault { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> DiscountDays { get; set; }
        public string PaymentTermCode { get; set; }
        public byte[] Updated_Timestamp { get; set; }
    }
}
